### ISSUE TITLE
"Text Encryption Based on Glider"

### ISSUE THREAD

**Issue by danivolo** [l1uk/DIY-Cryptography#1]
Una volta completato l'AND, così che ci abbiamo preso la mano, invece che costruire lo XOR come NOT (A AND B) AND (A OR B) potremmo fare un design originale per la singola porta. Alla fine è una singola porta, è probabile che si riesca a costruirla usando solo la logica dei flussi di glider.

**Comment by danivolo** [comment]
In Golly>Help>Online Archives>Golly Script Database>save.bmp.py o save-image.py potrebbero tornarci utili

**Comment by l1uk** [comment]
Logica ok, volendo implementare riflessione per controllare un singolo punto invece che due
